CC=clang
CFLAGS=-O3 -g -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda
LIBS=-lm
OBJ=laplace.o
TARGET=laplace

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) $(LIBS) -o $@ $^

clean:
	rm -f $(TARGET) *.o
